services:
  producer:
    image: producer
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  consumer:
    image: consumer
    ports:
      - "8082:8082"
